/* GENERATED by tools/anim2c.py from lineSweep.json -- DO NOT EDIT.
 * Regenerate with:
 *   python tools/anim2c.py Core/Src/lineSweep.json --fps 20.0 --kbps 38.4
 */
#include "animation_data.h"

/* Every point of every frame, back to back. 128 points. */
static const cc1101_point_t animation_points[128] = {
    /* frame 0: 2 points (1 spans) */
    { 24, 32}, { 24,224},
    /* frame 1: 2 points (1 spans) */
    { 30, 32}, { 30,224},
    /* frame 2: 2 points (1 spans) */
    { 37, 32}, { 37,224},
    /* frame 3: 2 points (1 spans) */
    { 44, 32}, { 44,224},
    /* frame 4: 2 points (1 spans) */
    { 50, 32}, { 50,224},
    /* frame 5: 2 points (1 spans) */
    { 56, 32}, { 56,224},
    /* frame 6: 2 points (1 spans) */
    { 63, 32}, { 63,224},
    /* frame 7: 2 points (1 spans) */
    { 70, 32}, { 70,224},
    /* frame 8: 2 points (1 spans) */
    { 76, 32}, { 76,224},
    /* frame 9: 2 points (1 spans) */
    { 82, 32}, { 82,224},
    /* frame 10: 2 points (1 spans) */
    { 89, 32}, { 89,224},
    /* frame 11: 2 points (1 spans) */
    { 96, 32}, { 96,224},
    /* frame 12: 2 points (1 spans) */
    {102, 32}, {102,224},
    /* frame 13: 2 points (1 spans) */
    {108, 32}, {108,224},
    /* frame 14: 2 points (1 spans) */
    {115, 32}, {115,224},
    /* frame 15: 2 points (1 spans) */
    {122, 32}, {122,224},
    /* frame 16: 2 points (1 spans) */
    {128, 32}, {128,224},
    /* frame 17: 2 points (1 spans) */
    {134, 32}, {134,224},
    /* frame 18: 2 points (1 spans) */
    {141, 32}, {141,224},
    /* frame 19: 2 points (1 spans) */
    {148, 32}, {148,224},
    /* frame 20: 2 points (1 spans) */
    {154, 32}, {154,224},
    /* frame 21: 2 points (1 spans) */
    {160, 32}, {160,224},
    /* frame 22: 2 points (1 spans) */
    {167, 32}, {167,224},
    /* frame 23: 2 points (1 spans) */
    {174, 32}, {174,224},
    /* frame 24: 2 points (1 spans) */
    {180, 32}, {180,224},
    /* frame 25: 2 points (1 spans) */
    {186, 32}, {186,224},
    /* frame 26: 2 points (1 spans) */
    {193, 32}, {193,224},
    /* frame 27: 2 points (1 spans) */
    {200, 32}, {200,224},
    /* frame 28: 2 points (1 spans) */
    {206, 32}, {206,224},
    /* frame 29: 2 points (1 spans) */
    {212, 32}, {212,224},
    /* frame 30: 2 points (1 spans) */
    {219, 32}, {219,224},
    /* frame 31: 2 points (1 spans) */
    {226, 32}, {226,224},
    /* frame 32: 2 points (1 spans) */
    {232, 32}, {232,224},
    /* frame 33: 2 points (1 spans) */
    {226, 32}, {226,224},
    /* frame 34: 2 points (1 spans) */
    {219, 32}, {219,224},
    /* frame 35: 2 points (1 spans) */
    {212, 32}, {212,224},
    /* frame 36: 2 points (1 spans) */
    {206, 32}, {206,224},
    /* frame 37: 2 points (1 spans) */
    {200, 32}, {200,224},
    /* frame 38: 2 points (1 spans) */
    {193, 32}, {193,224},
    /* frame 39: 2 points (1 spans) */
    {186, 32}, {186,224},
    /* frame 40: 2 points (1 spans) */
    {180, 32}, {180,224},
    /* frame 41: 2 points (1 spans) */
    {174, 32}, {174,224},
    /* frame 42: 2 points (1 spans) */
    {167, 32}, {167,224},
    /* frame 43: 2 points (1 spans) */
    {160, 32}, {160,224},
    /* frame 44: 2 points (1 spans) */
    {154, 32}, {154,224},
    /* frame 45: 2 points (1 spans) */
    {148, 32}, {148,224},
    /* frame 46: 2 points (1 spans) */
    {141, 32}, {141,224},
    /* frame 47: 2 points (1 spans) */
    {134, 32}, {134,224},
    /* frame 48: 2 points (1 spans) */
    {128, 32}, {128,224},
    /* frame 49: 2 points (1 spans) */
    {122, 32}, {122,224},
    /* frame 50: 2 points (1 spans) */
    {115, 32}, {115,224},
    /* frame 51: 2 points (1 spans) */
    {108, 32}, {108,224},
    /* frame 52: 2 points (1 spans) */
    {102, 32}, {102,224},
    /* frame 53: 2 points (1 spans) */
    { 96, 32}, { 96,224},
    /* frame 54: 2 points (1 spans) */
    { 89, 32}, { 89,224},
    /* frame 55: 2 points (1 spans) */
    { 82, 32}, { 82,224},
    /* frame 56: 2 points (1 spans) */
    { 76, 32}, { 76,224},
    /* frame 57: 2 points (1 spans) */
    { 70, 32}, { 70,224},
    /* frame 58: 2 points (1 spans) */
    { 63, 32}, { 63,224},
    /* frame 59: 2 points (1 spans) */
    { 56, 32}, { 56,224},
    /* frame 60: 2 points (1 spans) */
    { 50, 32}, { 50,224},
    /* frame 61: 2 points (1 spans) */
    { 44, 32}, { 44,224},
    /* frame 62: 2 points (1 spans) */
    { 37, 32}, { 37,224},
    /* frame 63: 2 points (1 spans) */
    { 30, 32}, { 30,224},
};

/* Where each frame starts in the pool, and how long it is. */
static const anim_frame_t animation_frames[64] = {
    {     0,    2 },   /* frame 0 */
    {     2,    2 },   /* frame 1 */
    {     4,    2 },   /* frame 2 */
    {     6,    2 },   /* frame 3 */
    {     8,    2 },   /* frame 4 */
    {    10,    2 },   /* frame 5 */
    {    12,    2 },   /* frame 6 */
    {    14,    2 },   /* frame 7 */
    {    16,    2 },   /* frame 8 */
    {    18,    2 },   /* frame 9 */
    {    20,    2 },   /* frame 10 */
    {    22,    2 },   /* frame 11 */
    {    24,    2 },   /* frame 12 */
    {    26,    2 },   /* frame 13 */
    {    28,    2 },   /* frame 14 */
    {    30,    2 },   /* frame 15 */
    {    32,    2 },   /* frame 16 */
    {    34,    2 },   /* frame 17 */
    {    36,    2 },   /* frame 18 */
    {    38,    2 },   /* frame 19 */
    {    40,    2 },   /* frame 20 */
    {    42,    2 },   /* frame 21 */
    {    44,    2 },   /* frame 22 */
    {    46,    2 },   /* frame 23 */
    {    48,    2 },   /* frame 24 */
    {    50,    2 },   /* frame 25 */
    {    52,    2 },   /* frame 26 */
    {    54,    2 },   /* frame 27 */
    {    56,    2 },   /* frame 28 */
    {    58,    2 },   /* frame 29 */
    {    60,    2 },   /* frame 30 */
    {    62,    2 },   /* frame 31 */
    {    64,    2 },   /* frame 32 */
    {    66,    2 },   /* frame 33 */
    {    68,    2 },   /* frame 34 */
    {    70,    2 },   /* frame 35 */
    {    72,    2 },   /* frame 36 */
    {    74,    2 },   /* frame 37 */
    {    76,    2 },   /* frame 38 */
    {    78,    2 },   /* frame 39 */
    {    80,    2 },   /* frame 40 */
    {    82,    2 },   /* frame 41 */
    {    84,    2 },   /* frame 42 */
    {    86,    2 },   /* frame 43 */
    {    88,    2 },   /* frame 44 */
    {    90,    2 },   /* frame 45 */
    {    92,    2 },   /* frame 46 */
    {    94,    2 },   /* frame 47 */
    {    96,    2 },   /* frame 48 */
    {    98,    2 },   /* frame 49 */
    {   100,    2 },   /* frame 50 */
    {   102,    2 },   /* frame 51 */
    {   104,    2 },   /* frame 52 */
    {   106,    2 },   /* frame 53 */
    {   108,    2 },   /* frame 54 */
    {   110,    2 },   /* frame 55 */
    {   112,    2 },   /* frame 56 */
    {   114,    2 },   /* frame 57 */
    {   116,    2 },   /* frame 58 */
    {   118,    2 },   /* frame 59 */
    {   120,    2 },   /* frame 60 */
    {   122,    2 },   /* frame 61 */
    {   124,    2 },   /* frame 62 */
    {   126,    2 },   /* frame 63 */
};

const anim_clip_t animation_clip = {
    .points   = animation_points,
    .frames   = animation_frames,
    .n_frames = 64,
};
