/*
 * animation.h
 *
 *  Created on: Sep 4, 2026
 *      Author: Nymph
 */

/*
 * animation.h -- paced playback of a vector animation over the CC1101 link.
 *
 * WHAT THIS IS FOR
 * ----------------
 * cc1101_send_frame() sends a frame as fast as the radio allows, so a frame
 * of 10 spans goes out in ~1 ms and a frame of 392 spans takes ~50 ms. Play a
 * clip that way and the animation SPRINTS through sparse frames and CRAWLS
 * through dense ones -- the playback speed ends up being a function of how
 * complicated the picture is, which is not what anyone wants.
 *
 * This module fixes the cadence: every frame occupies the same wall-clock
 * period, no matter how much data it needed. That is all "20 fps" actually
 * means.
 *
 * WHERE THE PACING BELONGS, AND WHY IT IS HERE
 * --------------------------------------------
 * On the transmitter, for three reasons:
 *
 *   1. Only this side knows the intended rate. The FPGA just redraws whatever
 *      is in PointRam; it has no idea what "correct speed" means.
 *   2. It needs no RTL change. topRF.sv swaps banks when a complete frame has
 *      landed AND the scanout wraps -- that stays exactly as it is.
 *   3. It preserves the no-ACK, self-healing protocol. Gating the swap on an
 *      FPGA timer instead would tangle with RxSeq.sv's deliberate "if the EOF
 *      packet is lost, hold the previous frame" behaviour.
 *
 * PACING IS NOT THE SAME AS SPEED
 * -------------------------------
 * This module makes frames EVENLY SPACED. It does not decide how many frames
 * per second your source material should play at. If the clip was authored at
 * 30 fps and you play it at 20, it will be perfectly smooth and running at
 * two-thirds speed. Drop source frames in the converter to keep real time.
 *
 * THE DATA LIVES IN FLASH
 * -----------------------
 * The F410RB has no filesystem, so animations are converted on the host by
 * tools/anim2c.py and linked in as `const` tables. cc1101_send_frame() takes a
 * const pointer, so frames are transmitted straight out of flash and never
 * occupy RAM.
 *
 * USAGE
 * -----
 *     #include "animation.h"
 *     #include "animation_data.h"
 *
 *     static animation_t anim;
 *     animation_init(&anim, &animation_clip, 20);
 *
 *     while (1) {
 *         animation_tick(&anim);      // non-blocking; sends when due
 *         ... other work ...
 *     }
 */

#ifndef INC_ANIMATION_H_
#define INC_ANIMATION_H_

#include "cc1101.h"
#include <stdint.h>
#include <stdbool.h>

/*
 * One frame, as a window into the clip's flat point pool.
 *
 * Frames are stored as (offset, length) into one big array rather than as an
 * array of arrays: it avoids a pointer table, keeps everything contiguous in
 * flash, and makes the whole clip one relocatable blob.
 */
typedef struct {
    uint16_t offset;     /* index of this frame's first point in `points` */
    uint16_t n_points;   /* always EVEN -- points are span endpoints      */
} anim_frame_t;

/*
 * A whole animation. Generated by tools/anim2c.py; always `const`, always in
 * flash. Never modified at runtime.
 */
typedef struct {
    const cc1101_point_t *points;    /* every point of every frame, back to back */
    const anim_frame_t   *frames;    /* where each frame sits in `points`        */
    uint16_t              n_frames;
} anim_clip_t;

/*
 * Playback state. One per clip being played; you almost certainly want exactly
 * one. Treat the fields as read-only from outside -- use the functions below.
 */
typedef struct {
    const anim_clip_t *clip;
    uint32_t period_ms;        /* wall-clock time each frame must occupy   */
    uint32_t next_deadline;    /* absolute tick when the next frame is due */
    uint16_t index;            /* which frame goes out next               */
    bool     running;

    /* ---- statistics, for the once-a-second report in main ---- */
    uint32_t frames_sent;      /* frames where every packet was accepted   */
    uint32_t frames_failed;    /* at least one packet failed to transmit   */
    uint32_t frames_late;      /* frames that overran their time budget    */
    uint32_t loops;            /* completed passes over the clip           */
} animation_t;

/*
 * Bind a clip and set the rate. Playback starts immediately; the first frame
 * goes out on the next animation_tick().
 *
 * fps is clamped to 1..1000. Note that the achievable rate is bounded by the
 * radio: at the config table's 500 kbps one 28-point packet is about 1.1 ms of
 * airtime, so 20 fps affords roughly 784 points (392 spans) per frame. At the
 * old 38.4 kbps it was only 84 points. anim2c.py checks this for your actual
 * clip and warns per frame.
 */
void animation_init(animation_t *a, const anim_clip_t *clip, uint16_t fps);

/*
 * Call as often as you like from the main loop. Does nothing until the next
 * frame is due, then transmits one frame and returns true.
 *
 * Returns true only on the tick that actually sent a frame, so it doubles as
 * "a frame just went out" for logging. Non-blocking apart from the transmit
 * itself, which blocks for that frame's airtime.
 */
bool animation_tick(animation_t *a);

/* Pause without losing position. The schedule resumes from `now` on start. */
void animation_stop(animation_t *a);
void animation_start(animation_t *a);

/* Jump back to frame 0 and restart the schedule. Statistics are preserved. */
void animation_rewind(animation_t *a);

/* Change rate mid-playback. Takes effect from the next frame. */
void animation_set_fps(animation_t *a, uint16_t fps);

/* Points in the frame that will go out next -- handy for a status print. */
uint16_t animation_next_points(const animation_t *a);

#endif /* INC_ANIMATION_H_ */
