/* GENERATED by tools/anim2c.py from lineSweep.json -- DO NOT EDIT.
 * Regenerate with:
 *   python tools/anim2c.py Core/Src/lineSweep.json --fps 20.0 --kbps 38.4
 */
#ifndef INC_ANIMATION_DATA_H_
#define INC_ANIMATION_DATA_H_

#include "animation.h"

extern const anim_clip_t animation_clip;

#endif /* INC_ANIMATION_DATA_H_ */
