/* GENERATED by tools/anim2c.py from badapple.json -- DO NOT EDIT.
 * Regenerate with:
 *   python tools/anim2c.py .\Core\Src\badapple.json --fps 20.0 --kbps 250.0
 */
#ifndef INC_ANIMATION_DATA_H_
#define INC_ANIMATION_DATA_H_

#include "animation.h"

extern const anim_clip_t animation_clip;

#endif /* INC_ANIMATION_DATA_H_ */
