## Debug (ILA) constraints -- AUTO-GENERATED by Vivado "Set Up Debug".
##
## Cleared for milestone 6: the debug net set changed again (TX nets added,
## milestone-4 config-test nets removed), so every probe previously in this file
## was stale. Re-run Tools > Set Up Debug on the synthesized design to
## repopulate it. Do not hand-edit.
##
## Suggested milestone-6 trigger:  a_tx_done == 1
## Then read:  a_txbytes   expect 0x03  (1 length byte + 2 payload bytes)
##             a_marcstate expect 0x13  (TX); 0x01 means STX never took
##             a_sync_seen / a_sent_ok / a_timeout / a_pkt_count / gdo0_s
